exclude: >
        (?x)(
            lib/kalkulator2018.py|
            .bumpversion.cfg|
            js_src/vendor/|
            lib/(py2js|gae_mini_profiler|appengine-toolkit)/|
            static/js/kalkulation.js$
        )

repos:
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: v1.4.0-1
  hooks:
  - id: fix-encoding-pragma
  - id: trailing-whitespace
  - id: check-ast
  - id: double-quote-string-fixer
  - id: check-docstring-first
  - id: flake8
    additional_dependencies:
    - flake8-docstrings
    # uses tox.ini
  - id: check-builtin-literals
    args: ['--no-allow-dict-kwargs']
  - id: requirements-txt-fixer
  - id: check-yaml
  - id: check-json
  - id: pretty-format-json
    args: ['--autofix']
  - id: check-xml
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: name-tests-test
  - id: check-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: check-executables-have-shebangs
- repo: git://github.com/FalconSocial/pre-commit-python-sorter
  sha: b57843b0b874df1d16eb0bef00b868792cb245c2
  # uses tox.ini
  hooks:
  - id: python-import-sorter
  # args: ['-a', 'from __future__ import unicode_literals']
- repo: https://github.com/asottile/pyupgrade
  sha: v1.8.0
  hooks:
  - id: pyupgrade
- repo: https://github.com/mdornseif/standardjs-mirror.git
  sha: 7fda18f6d6608c1424d8253eb9a0f1b668c4a3ef
  hooks:
  - id: standard
    args:
    - --parser babel-eslint
    - --fix
    exclude: >
            (?x)(
                /js_src/vendor/|
                /lib/(py2js|gae_mini_profiler|appengine-toolkit)/|
                /static/js/kalkulation.js$
            )
    always_run: false
    # log_file: standard.log
