repos:
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: v1.2.0
  hooks:
  - id: flake8
    args: ['--max-line-length=110', '--ignore=E712,E722']
  - id: check-builtin-literals
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
  - id: fix-encoding-pragma
  # /pretty_format_json --autofix --no-ensure-ascii --no-sort-keys
  # check_ast.py
- repo: git://github.com/FalconSocial/pre-commit-python-sorter
  sha: 1.0.4
  hooks:
    - id: python-import-sorter
    # args: ['--silent-overwrite']
- repo: https://github.com/asottile/pyupgrade
  sha: v1.2.0
  hooks:
    - id: pyupgrade
