#!/usr/bin/env python
# encoding: utf-8
"""
application.py - `WSGIApplication` generation.

Created by Maximillian Dornseif on 2016-04-28.
Copyright (c) 2016, 2017 Maximillian Dornseif. MIT licensed.
"""

import cgitb
import logging

import webapp2

from google.appengine.api import users
from google.appengine.ext import ndb

from .tools.config import is_production


def make_app(url_mapping, error_handlers=None):
    """Generate a WSGI-Appfrom an url mapping."""
    app = webapp2.WSGIApplication(url_mapping, debug=(not is_production()))
    # app.error_handlers[404] = handle_404
    # app.error_handlers[400] = handle_500  # 400 is generated by `auftrag_anlegen()`
    # app.error_handlers[500] = handle_500
    if error_handlers:
        for code in error_handlers:
            app.error_handlers[code] = error_handlers[code]
    return ndb.toplevel(app)


# Das fängt leider kein runtime.DeadlineExceededError
class WSGIApplication(webapp2.WSGIApplication):
    u"""Stellt sicher, dass wir auch BaseException fangen können."""

    def __call__(self, environ, start_response):
        """Wrap WSGI call with minimal error reporting."""
        try:
            return super(WSGIApplication, self).__call__(environ, start_response)
        except:
            logging.critical("__call__(): uncaught error")
            raise

    def handle_exception(self, request, response, e):
        """Handle exceptions in request handlers, generating a cgitb in development mode."""
        if isinstance(e, webapp2.HTTPException):
            code = e.code
        else:
            code = 500

        handler = self.error_handlers.get(code)
        if handler:
            return handler(request, response, e)
        else:
            if code >= 500 and users.is_current_user_admin() and not is_production():
                # clear output and set to HTML
                response.clear()
                response.headers['Content-Type'] = 'text/html'
                handler = cgitb.Hook(file=response.out).handle
                handler()
            # Re-raise it to be caught by the WSGI app.
            raise
